### ISSUE TITLE
Upgrade rust toolchain to stable

### ISSUE THREAD

**Issue by chaoticlonghair** [citahub/cita-common#179]
Since we put lots of crates in this repository, and we update this repository too often recently, so it will be a hard job.

I think we should split this big job into several jobs:
- [x] Remove some unstable `#![feature]` and `#![rustfmt_skip]`. (#196)
- [x] Remove the features which still are unstable, such as `TryInto` and `TryFrom`, write code to replace them. (#197)
- [x] Upgrade the rust to stable. (#198)
      Some features was stable, now, for example: proc-macro.
